### DISCUSSION TITLE
Can't install coturn on its own

### DISCUSSION THREAD

**Discussion by ghost** [JGoutin/ansible_home#60] [Q&A] [answered]
Not sure if I am doing something wrong - but using the exact playbook from the documentation (and having installed the collection earlier) I get 
```ERROR! the role 'coturn' was not found in jgoutin.home:ansible.legacy```

```The offending line appears to be:

  roles:
    - coturn
      ^ here
```

And my playbook is:
```
- hosts: turn_stun
  become: true
  collections:
    - jgoutin.home
  roles:
    - coturn
  vars:
    coturn_realm: myactualdomain.com
    coturn_static_auth_secret: my_secret_password
```
I did see in the main readme it talks about coturn being a dependency, but I don't need anything else done, really - just this
