### ISSUE TITLE
common: Configure journal max size

### ISSUE THREAD

**Issue by JGoutin** [JGoutin/ansible_home#57]
Allow to configure journald disk and memory usage:

```ini
[Journal]
SystemMaxUse={{ common_journal_disk_max_size }}
RuntimeMaxUse={{ common_journal_memory_max_size }}
```

```yaml
- name: Ensure journald configuration directory is present
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: 0640

- name: Ensure journald is configured
  ansible.builtin.template:
    src: journald-max-use.conf.j2
    dest: /etc/systemd/journald.conf.d/max-use.conf
    mode: 0600
```
